UPDATE product_images SET path='IMG_C/CТИМУЛ NPK 200г (пакет) для Газонів, декор.трав, 1 шт.webp' WHERE path='IMG_C/CТИМУЛ NPK 200г (пакет) для Газонів, декор.трав, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Гортензій, вересових рослин, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Гортензій, вересових рослин, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Винограду, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Винограду, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Квітучих рослин,1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Квітучих рослин,1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Лохини,чорниці,журавлини, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Лохини,чорниці,журавлини, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Огірків,кабачків, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Огірків,кабачків, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Плодових та ягідних кущів, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Плодових та ягідних кущів, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Полуниці та суниці, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Полуниці та суниці, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Розсади, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Розсади, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Петуній,сурфіній, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Петуній,сурфіній, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Троянд, хризантем, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Троянд, хризантем, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Томатів, перцю, баклажанів, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Томатів, перцю, баклажанів, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Цибулі, часнику, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Цибулі, часнику, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Саду та городу універсальне, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Саду та городу універсальне, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) для Хвойних, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) для Хвойних, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) Укорінювач, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) Укорінювач, 1 шт..webp';
UPDATE product_images SET path='IMG_C/СТИМУЛ NPK 200г (пакет) Універсал для кімнатних, 1 шт.webp' WHERE path='IMG_C/СТИМУЛ NPK 200г (пакет) Універсал для кімнатних, 1 шт..webp';
UPDATE product_images SET path='IMG_M/Держак до плоскоріза, шт.webp' WHERE path='IMG_M/Держак до плоскоріза, шт..webp';
UPDATE product_images SET path='IMG_M/Граблі прямі 300х90 мм пласт.ручка Мастертул.webp' WHERE path='IMG_M/Граблі прямі 300х90 мм пласт..ручка Мастертул.webp';
UPDATE product_images SET path='IMG_M/Душ Вертушка 2-ход. вел.webp' WHERE path='IMG_M/Душ Вертушка 2-ход. вел..webp';
UPDATE product_images SET path='IMG_M/Душ Вертушка 4-ход. вел.jpg' WHERE path='IMG_M/Душ Вертушка 4-ход. вел..jpg';
UPDATE product_images SET path='IMG_M/Душ Вертушка 5-ход. вел.jpg' WHERE path='IMG_M/Душ Вертушка 5-ход. вел..jpg';
UPDATE product_images SET path='IMG_M/Душ Вертушка 3-ход. вел.jpg' WHERE path='IMG_M/Душ Вертушка 3-ход. вел..jpg';
UPDATE product_images SET path='IMG_N4/Керамзит Садівник, 1 л.webp' WHERE path='IMG_N4/Керамзит Садівник, 1 л..webp';
UPDATE product_images SET path='IMG_N6/Редька Чорна зимова Кулата, 2г Проф.Нас.webp' WHERE path='IMG_N6/Редька Чорна зимова Кулата, 2г Проф.Нас..webp';
UPDATE product_images SET path='IMG_N7/Горщик для розсади d 7 см  6,0 0,16л теракот кругл.jpg' WHERE path='IMG_N7/Горщик для розсади d 7 см  6,0 0,16л теракот кругл..jpg';
UPDATE product_images SET path='IMG_N7/Торфяний горщик 11 10 1 шт.webp' WHERE path='IMG_N7/Торфяний горщик 11 10 1 шт..webp';
UPDATE product_images SET path='IMG_N7/Торфяний горщик 8 8 1 шт.webp' WHERE path='IMG_N7/Торфяний горщик 8 8 1 шт..webp';
UPDATE product_images SET path='IMG_N7/Торфяний горщик 6 6 1 шт.webp' WHERE path='IMG_N7/Торфяний горщик 6 6 1 шт..webp';
UPDATE product_images SET path='IMG_N8/Корм МЯУ Коти вологий 85 г в ас.webp' WHERE path='IMG_N8/Корм МЯУ Коти вологий 85 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р SELECTION Коти вологий 80 г в ас.webp' WHERE path='IMG_N8/Корм С4Р SELECTION Коти вологий 80 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р Коти вологий 80 г Спеціал.webp' WHERE path='IMG_N8/Корм С4Р Коти вологий 80 г Спеціал..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р Коти вологий 85 г в ас.webp' WHERE path='IMG_N8/Корм С4Р Коти вологий 85 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р Коти ласощі 5 г в ас.webp' WHERE path='IMG_N8/Корм С4Р Коти ласощі 5 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р Кошенята вологий 80 г в ас.webp' WHERE path='IMG_N8/Корм С4Р Кошенята вологий 80 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р Собаки ласощі 12 г в ас.webp' WHERE path='IMG_N8/Корм С4Р Собаки ласощі 12 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм С4Р Цуценята вологий 100 г в ас.webp' WHERE path='IMG_N8/Корм С4Р Цуценята вологий 100 г в ас..webp';
UPDATE product_images SET path='IMG_N8/Корм-крекер Колосок для гризунів 140 г.webp' WHERE path='IMG_N8/Корм-крекер Колосок для гризунів 140 г..webp';
UPDATE product_images SET path='IMG_N8/Корм-крекер Колосок для папуг в асорт.webp' WHERE path='IMG_N8/Корм-крекер Колосок для папуг в асорт..webp';
UPDATE product_images SET path='IMG_U1/Капуста Амагер пр.jpg' WHERE path='IMG_U1/Капуста Амагер пр..jpg';
UPDATE product_images SET path='IMG_U2/Контрик для самок 1 табл.jpg' WHERE path='IMG_U2/Контрик для самок 1 табл..jpg';
UPDATE product_images SET path='IMG_U2/Краплі Vitomax Альфа для собак 25-40 кг протипараз.webp' WHERE path='IMG_U2/Краплі Vitomax Альфа для собак 25-40 кг протипараз..webp';
UPDATE product_images SET path='IMG_U2/Контрик для самців 1 табл.webp' WHERE path='IMG_U2/Контрик для самців 1 табл..webp';
UPDATE product_images SET path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для котів до 4 кг протипараз.webp' WHERE path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для котів до 4 кг протипараз..webp';
UPDATE product_images SET path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для собак 10-30 кг протипараз.webp' WHERE path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для собак 10-30 кг протипараз..webp';
UPDATE product_images SET path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для котів 4-8 кг протипараз.webp' WHERE path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для котів 4-8 кг протипараз..webp';
UPDATE product_images SET path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для собак 4-10 кг протипараз.webp' WHERE path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для собак 4-10 кг протипараз..webp';
UPDATE product_images SET path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для собак до 4 кг протипараз.webp' WHERE path='IMG_U2/Краплі Vitomax ПЛАТІНУМ для собак до 4 кг протипараз..webp';
UPDATE product_images SET path='IMG_U2/Нашийник Супер Хелп для котів 35 см протипараз.webp' WHERE path='IMG_U2/Нашийник Супер Хелп для котів 35 см протипараз..webp';
UPDATE product_images SET path='IMG_U2/Нашийник Супер Хелп для кошенят 35 см протипараз.webp' WHERE path='IMG_U2/Нашийник Супер Хелп для кошенят 35 см протипараз..webp';
UPDATE product_images SET path='IMG_U3/Корм  МЯУ Коти вологий 85 г в ас.jpg' WHERE path='IMG_U3/Корм  МЯУ Коти вологий 85 г в ас..jpg';
UPDATE product_images SET path='IMG_U3/Корм  С4Р SELECTION Коти вологий 80 г в ас.jpg' WHERE path='IMG_U3/Корм  С4Р SELECTION Коти вологий 80 г в ас..jpg';
UPDATE product_images SET path='IMG_U3/Корм  С4Р Коти вологий 80 г Спеціал.webp' WHERE path='IMG_U3/Корм  С4Р Коти вологий 80 г Спеціал..webp';
UPDATE product_images SET path='IMG_U3/Корм  С4Р Коти вологий 85 г в ас.jpg' WHERE path='IMG_U3/Корм  С4Р Коти вологий 85 г в ас..jpg';
UPDATE product_images SET path='IMG_U3/Корм  С4Р Коти ласощі 5 г в ас.jpg' WHERE path='IMG_U3/Корм  С4Р Коти ласощі 5 г в ас..jpg';
UPDATE product_images SET path='IMG_U3/Корм  С4Р Кошенята вологий 80 г в ас.webp' WHERE path='IMG_U3/Корм  С4Р Кошенята вологий 80 г в ас..webp';
UPDATE product_images SET path='IMG_U3/Корм  С4Р Собаки ласощі 12 г в ас.jpg' WHERE path='IMG_U3/Корм  С4Р Собаки ласощі 12 г в ас..jpg';
UPDATE product_images SET path='IMG_U3/Корм  С4Р Цуценята вологий 100 г в ас.webp' WHERE path='IMG_U3/Корм  С4Р Цуценята вологий 100 г в ас..webp';
UPDATE product_images SET path='IMG_U7/Горщик для розсади d = 7 см х 6,0 0,16л теракот кругл.jpg' WHERE path='IMG_U7/Горщик для розсади d = 7 см х 6,0 0,16л теракот кругл..jpg';
UPDATE product_images SET path='IMG_U3/Мясо-кісткове борошно 63 протеїн 1 кг с х.jpg' WHERE path='IMG_U3/Мясо-кісткове борошно 63% протеїн 1 кг с х.jpg';
UPDATE product_images SET path='IMG_U6/Сітка пластикова затіняюча 4 м х 50 м 45 затінення.webp' WHERE path='IMG_U6/Сітка пластикова затіняюча 4 м х 50 м 45% затінення.webp';
UPDATE product_images SET path='IMG_U7/Мясо-кісткове борошно 63 протеїн 1 кг.jpg' WHERE path='IMG_U7/Мясо-кісткове борошно 63% протеїн 1 кг.jpg';
