UPDATE product_content SET active_ingredient='гліфосат' WHERE pid=676;
UPDATE product_content SET active_ingredient='гліфосат' WHERE pid=715;
UPDATE product_content SET active_ingredient='абамектин' WHERE pid=1128;
UPDATE product_content SET active_ingredient='метаризин' WHERE pid=1139;
UPDATE product_content SET active_ingredient='метальдегід' WHERE pid=1153;
UPDATE product_content SET active_ingredient='борна кислота' WHERE pid=1870;
UPDATE product_content SET active_ingredient='борна кислота' WHERE pid=1871;
UPDATE product_content SET active_ingredient='бурштинова кислота' WHERE pid=1872;
UPDATE product_content SET active_ingredient='гетероауксин' WHERE pid=1877;
UPDATE product_content SET active_ingredient='гумат калію' WHERE pid=1881;
UPDATE product_content SET active_ingredient='гумат натрію' WHERE pid=1882;
UPDATE product_content SET active_ingredient='гіберелін' WHERE pid=1891;
UPDATE product_content SET active_ingredient='залізний купорос' WHERE pid=2186;
UPDATE product_content SET active_ingredient='залізний купорос' WHERE pid=2187;
UPDATE product_content SET active_ingredient='йод' WHERE pid=2192;
UPDATE product_content SET active_ingredient='мідь' WHERE pid=2203;
UPDATE product_content SET active_ingredient='мідний купорос' WHERE pid=2204;
UPDATE product_content SET active_ingredient='мідний купорос' WHERE pid=2205;
UPDATE product_content SET active_ingredient='мідний купорос' WHERE pid=2206;
UPDATE product_content SET active_ingredient='мідь' WHERE pid=2207;
UPDATE product_content SET active_ingredient='сірка' WHERE pid=2226;
UPDATE product_content SET active_ingredient='сірка' WHERE pid=2227;
UPDATE product_content SET active_ingredient='сірка' WHERE pid=2228;
UPDATE product_content SET active_ingredient='сірка' WHERE pid=2238;
UPDATE product_content SET active_ingredient='триходерма' WHERE pid=2241;
UPDATE product_content SET active_ingredient='сірка' WHERE pid=2261;
